version: '3'

services:
  app-podman:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - db-podman

    environment:
      SQL_HOST: db-podman
      ConnectionStrings__PokemonConection: "Server=db-podman,1433;Database=PokemonesDB;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;"

    volumes:
      - ../..:/workspaces:cached,Z

    command: sleep infinity

    user: root

  db-podman:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
